### ISSUE TITLE
New feature for downloading and saving

### ISSUE THREAD

**Issue by ImmutableBox** [ThomasLuu00/micro-note#1]
New feature to download and save the note text entered by the user. 

This will allow the user to:

- Have a copy of their note 
- Save the note on their local machine
- Read their note offline

This change will be adding a new button the user can click on to save their note. Will be using [FileSaver.js](https://github.com/eligrey/FileSaver.js) to implement this functionality.

I would like to work on this feature.

Best Regards,
Paul Luu

**Comment by ThomasLuu00** [comment]
OK

**Comment by ThomasLuu00** [comment]
Approved.
